### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by AkiraVoid** [acidicoala/UplayR2Unlocker#1]
I use Chinese as my native language.

**Information**

Game: Assassin's Creed: Valhalla
Game Version: 1.2.2
System: Windows 10 20H2 (OS: 19042.1052)

The language setting in Ubisoft Connect has already been set to Chinese.

The `WARNING` screen is in Chinese.

**Reproduce**

1. Start game without unlocker;
2. The language is Chinese and can be changed by Options>Interface>Language;
3. Quit the game;
3. Add unlocker and rename origin file;
4. Restart the game;
5. The language is changed to English and cannot be changed by Options>Interface>Language;

**What I've done to solve this problem**

1. I edited the `ACValhalla.ini` directly but nothing happen. In fact, the language settings was re-changed to `en-US` after I restart the game.

**Comment by acidicoala** [comment]
You haven't shared the only thing that is worth looking at - contents of the config file.

**Comment by AkiraVoid** [comment]
Here it is"

```
[Language]
Client=zh-CN
Text=zh-CN
Sound=en-US
Subtitles=zh-CN
[Graphics]
AdapterVendorID=4318
AdapterDeviceID=7943
MonitorDesc=
DisplayIndex=0
WindowPosX=0
WindowPosY=0
FullscreenWidth=1920
FullscreenHeight=1080
WindowedWidth=1920
WindowedHeight=1080
WindowMaximised=0
RefreshRate=0
WindowMode=2
VSyncMode=0
MaxFPS=75
IsFpsLimitEnabled=0
PixelDensity=1.00000
LastUsedFullscreenMode=1
KeepStandardAspect=0
HDREnabled=0
Freesync2Enabled=0
AdaptiveQuality=0
Antialiasing=2
Bloom=1
Character=2
CharacterTexture=2
Cloud=3
Clutter=3
CrowdDensity=0
Culling=0
DOF=2
Environment=4
Fog=2
Lighting=0
MotionBlur=1
Rain=2
Reflection=1
Shadow=4
SSAO=2
Terrain=0
Tessellation=2
Texture=2
TextureFiltering=2
Water=2
[LightingDevices]
Config=[{"id":"MSI MysticLight SDK","enabled":true,"config":{"ip":"localhost","port":1462,"ambientPort":14621,"authToken":""}}]
Enabled=0
[Input]
InputSourcesSelectorMode=1
[Options]
Controller Feedback=4294967295
WideAspectStretchedHUDMode=1
KeyboardHighlightingMode=dynamic
FOVScale=1.00000
AutoFOV=0
LockCursorToTheWindow=0
TobiiEnabled=1
TobiiExtendedViewEnabled=1
TobiiAimAtGazeEnabled=1
TobiiMarkAtGazeEnabled=1
TobiiInteractAtGazeEnabled=1
TobiiLockTargetAtGazeEnabled=1
TobiiDynamicLightAdaptationEnabled=1
TobiiSunEffectsEnabled=1
TobiiHeadTrackingAutoResetEnabled=1
TobiiExtendedViewSensitivity=50
TobiiExtendedViewResponsiveness=50
TobiiEyeVsHeadTrackingRatio=100
[VoiceInput]
InputMode=1
[Startup]

```

**Comment by AkiraVoid** [comment]
```
[Language]
Client=zh-CN
Text=zh-CN
Sound=en-US
Subtitles=zh-CN
```
`text` and `subtitles` will be reset to `en-US` after I restart the game, I haven't tried to change `sound` setting, other settings are fine.

**Comment by acidicoala** [comment]
Is this a joke? This is not a Uplay R2 unlocker config. Read the instructions in the forum topic from start to finish: https://cs.rin.ru/forum/viewtopic.php?f=29&t=111874.
